/****************************************************************************************************
*  File name: csci.c
*
*  Purpose: Definition of the CSCI
*
*  Copyright Notice:
*  All source code and data contained in this file is Proprietary and
*  Confidential to Eaton Aerospace, and must not be reproduced, transmitted, or
*  disclosed; in whole or in part, without the express written permission of
*  Eaton Aerospace.
*
*  Copyright (c) 2022 - Eaton Aerospace Group, All Rights Reserved.
*
*  Author            Date       CR#          Description
*  ------           ---------   ------     ---------------------------------------
*  Adam Bouwens     12/07/2022  N/A        Ported to MCU
*
****************************************************************************************************/


/******************** INCLUDES ********************/
#include "F28x_Project.h"
#include "csci.h"

/*Justification for Coding Standard Deviation:
 *    C_int00 defined in assembly
 *    An exception to MISRA Rule 8.1 and 8.9 is required.
 */
/*lint -e{937} # intended as is */
/*lint -e{960} # intended as is */
extern void c_int00();

/******************** DEFINES ********************/
#define SW_VERSION_MAJOR        1   /* Software Version Major */
#define SW_VERSION_MINOR        7   /* Software Version Minor */
#define SW_VERSION_REVISION     1   /* Software Version Revision */
#define SW_VERSION_BUILD        0   /* Software Version Build */
#define LRU_NAME                ("MCU_OFP")
#define HW_PN                   ("0000")

/******************** CONSTANTS ********************/

const CSCI_TypeHeader CSCI_APP_HEADER =
{
    0x709509A0U,                      /* CRC This gets generated by hex2A665.exe */
    &c_int00,                         /* CodeEntryPoint */
    0x67FFEU,                         /* ImageSize in Bytes APP 0x084000 to 0xB7FFF*/
    sizeof(CSCI_TypeHeader) * 2U,     /* HeaderSize (bytes) */
    0x5678U,                          /* BCID_Group[2] */
    0x1234U,                          /* BCID_Number */
    { LRU_NAME },                     /* CSCI_Name[16] */
    { /* tSwVersion_t: */
      (uint16_t)SW_VERSION_MAJOR,     /* tSwVersion_t:  Major */
      (uint16_t)SW_VERSION_MINOR,     /* tSwVersion_t:  Minor */
      (uint16_t)SW_VERSION_REVISION,  /* tSwVersion_t:  Revision */
      (uint16_t)SW_VERSION_BUILD      /* tSwVersion_t:  Build */
    },
    { HW_PN },                        /* HWUPN[16] */
    { 0U, 0U, 0U }                    /* AircraftType[2] */
};

#pragma DATA_SECTION(CSCI_PDI_HEADER, "PDI_CSCI_HDR");
const CSCI_TypeHeader CSCI_PDI_HEADER;

#pragma DATA_SECTION(CSCI_BLD_HEADER, "BLD_CSCI_HDR");
const CSCI_TypeHeader CSCI_BLD_HEADER;
